State tracking
AlexandrShcherbakov/etna pull request #16
Opened 2022-11-03 21:53 UTC by AlexandrShcherbakov

2022-11-03 22:12 UTC, Mrkol requested changes
Что-то мне не нравится такой дизайн если честно. Почему бы не сделать обёртку над vk::CommandBuffer и не поместить весь трекинг в неё?

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +void ResourceStates::setTextureState(VkCommandBuffer com_buffer, VkImage image,
Опять сишный интерфейс вместо плюсового, VkImage -> vk::Image

2022-11-03 22:12 UTC, Mrkol commented on etna/source/GlobalContext.cpp
> +  GlobalContext::~GlobalContext() = default;
Зачем? Правило нуля же.

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +void ResourceStates::setRenderTarget(VkCommandBuffer com_buffer, VkImage image)
ColorTarget и DepthTarget по-моему более понятная терминология

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +    vk::ImageAspectFlagBits::eDepth);
eStencil тоже стоит поставить на всякий случай

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.hpp
> +  using HandleType = uint64_t;
По-моему лучше void* использовать чтобы случайно не сделать UB

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.hpp
> +    vk::AccessFlags2 accessFlags = vk::AccessFlags2();
У всех этих классов есть конструктор по умолчанию, явно инициализировать нет смысла

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.hpp
> +    vk::AccessFlags2 accessFlags = vk::AccessFlags2();
У всех этих классов есть конструктор по умолчанию, явно инициализировать нет смысла

2022-11-03 22:12 UTC, Mrkol commented on etna/source/StateTracking.hpp
> +    bool operator==(const TextureState &other) const
У нас 20е плюсы, можно писать `bool operator==(const TextureState &other) const = default;` и оно само сгенерирует сравнение всех полей

2022-11-03 22:32 UTC, AlexandrShcherbakov commented on etna/source/GlobalContext.cpp
> +  GlobalContext::~GlobalContext() = default;
Что за правило?

2022-11-03 22:36 UTC, AlexandrShcherbakov commented on etna/source/StateTracking.hpp
> +  using HandleType = uint64_t;
А почему будет UB?

2022-11-03 22:39 UTC, AlexandrShcherbakov commented on etna/source/StateTracking.cpp
> +    vk::ImageAspectFlagBits::eDepth);
vkCmdPipelineBarrier2: Using format (VK_FORMAT_D16_UNORM) with aspect flags (VK_IMAGE_ASPECT_DEPTH_BIT|VK_IMAGE_ASPECT_STENCIL_BIT) but depth-only image formats can have only the VK_IMAGE_ASPECT_DEPTH_BIT set

2022-11-04 11:44 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +    vk::ImageAspectFlagBits::eDepth);
А, ну тогда надо проверить есть ли стенсил в текущем формате и только тогда ставить этот аспект, но не горит

2022-11-04 11:48 UTC, Mrkol commented on etna/source/StateTracking.hpp
> +  using HandleType = uint64_t;
Я всё перепутал, вопрос снят

2022-11-08 17:17 UTC, AlexandrShcherbakov commented
> Что-то мне не нравится такой дизайн если честно. Почему бы не сделать обёртку над vk::CommandBuffer и не поместить весь трекинг в неё?

А в чём глобальная разница будет?

2023-01-03 09:22 UTC, merged