Опция подавить создание барьеров при вызове createDescriptorSet
AlexandrShcherbakov/etna pull request #56
Opened 2024-11-21 12:38 UTC by Sazan1209

Добавил опцию подавить создание барьеров при вызове createDescriptorSet. Дефолтное поведение createDescriptorSet создаёт кучу проблем, которые нетривиально разрешить, а автоматическая генерация барьеров зачастую создаёт лишние зависимости

2024-11-22 20:41 UTC, Mrkol requested changes

2024-11-22 20:41 UTC, Mrkol commented on etna/include/etna/DescriptorSet.hpp
> +  };
Давай лучше отдельный файл с `enum class BarrierBehavior { Automatic, Manual };` и аналогичные ифы добавим в RenderTargetState тоже, а также глобальный флаг в инициализации этны чтобы подовить вообще все автоматические барьеры разом

2024-11-23 11:18 UTC, Sazan1209 commented on etna/include/etna/DescriptorSet.hpp
> +  };
Вроде сделал

2024-11-23 11:20 UTC, Sazan1209 commented
Добавил в InitParameters флаг для подавления генерации барьеров. По умолчанию, барьеры в CreateDescriptorSet и TargetRenderState генерятся в зависимости от этого флага, но можно также явно прописать, нужно ли их генерировать.

2024-11-23 11:49 UTC, Sazan1209 commented
Раз пошла такая пьянка, добавил ещё и возможность форсировать set_state. Изначально хотел через отдельный pr оформить, но потом решил что лучше два новых enum-а в одном файле лежат

2024-11-24 13:44 UTC, Mrkol requested changes

2024-11-24 13:44 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +  if (force == ForceSetState::eTrue && newState == oldState)
Выглядит будто перепутано, скипать надо если force == false && new == old

2024-11-24 13:44 UTC, Mrkol commented on etna/source/StateTracking.cpp
> +    (behavoir == BarrierBehavoir::eDefault && get_context().shouldGenerateBarriers()))
Вот это условие кажется скорее должно быть спрятано внутрь `get_context().shouldGenerateBarrierWhen(behavior)`

2024-11-24 15:02 UTC, Sazan1209 commented on etna/source/StateTracking.cpp
> +  if (force == ForceSetState::eTrue && newState == oldState)
Как обычно в глаза долблюсь. 50 раз перепроверил, и всё равно пропустил

2024-11-24 15:13 UTC, Sazan1209 commented on etna/source/StateTracking.cpp
> +  if (force == ForceSetState::eTrue && newState == oldState)
Fixed

2024-11-24 15:13 UTC, Sazan1209 commented on etna/source/StateTracking.cpp
> +    (behavoir == BarrierBehavoir::eDefault && get_context().shouldGenerateBarriers()))
Done

2024-11-24 17:23 UTC, merged